steps:
  # - name: gcr.io/cloud-builders/git
  #   args: ['fetch', '--unshallow']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo $$FIRESTORE_TOKEN']
    secretEnv: ['FIRESTORE_TOKEN']
  # build firebase tool
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'build_tools/firebase'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build -t gcr.io/$PROJECT_ID/firebase_builder:latest -f Dockerfile --build-arg FIRESTORE_TOKEN=$$FIRESTORE_TOKEN .',
      ]
    secretEnv: ['FIRESTORE_TOKEN']
  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/firebase_builder:latest']

    # test env variable
  - name: 'gcr.io/$PROJECT_ID/firebase_builder'
    entrypoint: 'bash'
    args: ['-c', 'echo ENV_FIRESTORE_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'ls -al']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build', 'api']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apipackage']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apidocker']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apijson']

  # Deploy to firebase
  - name: 'gcr.io/$PROJECT_ID/firebase_builder'
    args:
      [
        'deploy',
        '-P',
        '$PROJECT_ID',
        '--only',
        'hosting',
        '--token=ENV_FIRESTORE_TOKEN',
        '--debug',
      ]
    secretEnv: ['FIRESTORE_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/monorock-api', '.']
    dir: 'dist/apps/api'
  # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'monorockapi',
        '--image',
        'gcr.io/$PROJECT_ID/monorock-api',
        '--region',
        us-central1,
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

secrets:
  - kmsKeyName: projects/monorock/locations/global/keyRings/monorock-integration-secrets/cryptoKeys/monorock-firebase-token
    secretEnv:
      FIRESTORE_TOKEN: CiQAy0NVR7SUUqDhfL1ij6knHd9sIiLX/kgy8pBEeUPIBWnF3vwSkAEAlioXGAphMnchTae3mzJ8Mav88uqFX4AgZj9s5qnkXEmSsTdgNcKd+7E+XvMoY0tDfLHh4kjFZEjsVUhE30FORC6+rDmrdaSEYpJNJ7tmJ14mrWvhLAz7AOLAqoFA0l0+yGdiM2UQYPnU4xkx51uJgtu1AS146XaVgOjk69UpyTVF1r/twGSl8Jx7cmqbGAY=
