steps:
  # - name: gcr.io/cloud-builders/git - needed if you want a deep clone
  #   args: ['fetch', '--unshallow']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo $$FIRESTORE_TOKEN']
    secretEnv: ['FIRESTORE_TOKEN']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build', 'api']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apipackage']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apidocker']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apijson']

  # Deploy to firebase
  - name: 'gcr.io/$PROJECT_ID/firebase_builder'
    args:
      [
        'deploy',
        '-P',
        '{PROJECT_ID}',
        '--only',
        'hosting',
        '--token',
        '$$FIRESTORE_TOKEN',
      ]
    secretEnv: ['FIRESTORE_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/{PROJECT_ID}/monorock-api', '.']
    dir: 'dist/apps/api'
  # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'monorockapi',
        '--image',
        'gcr.io/{PROJECT_ID}/monorock-api',
        '--region',
        us-central1,
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

secrets:
  - kmsKeyName: projects/monorock/locations/global/keyRings/monorock-integration-secrets/cryptoKeys/monorock-firebase-token
    secretEnv:
      FIRESTORE_TOKEN: CiQAy0NVR66pWZveF8Sw8aTSs9/BBEdFkjubfxwsB1RZIDPzr6YSkAEAlioXGLtNE6JldirgqLvpz7DKjhOc3Zxc45UF1zp09FA8slpCSRamtJc9Pw/nbk9edzISJxgG85+eJ9ghgMazvsY5bTzJ1mBFiIxbLF5lEU7GNYITjL74EYik959ETgw6EPe6Iy9Qh14XCVCDaEzZbuXDbI+Ho4T8nXDUv4uWpj2QQ2NwntMENDhodCp2rFY=
