steps:
  # - name: gcr.io/cloud-builders/git
  #   args: ['fetch', '--unshallow']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo $$FIREBASE_TOKEN']
    secretEnv: ['FIREBASE_TOKEN']

  # build firebase tool
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'build_tools/firebase'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']

  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/firebase:latest']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['list']
    secretEnv: ['FIREBASE_TOKEN']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build']
  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'build', 'api']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apipackage']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apidocker']

  - name: 'gcr.io/$PROJECT_ID/nrwl_builder'
    args: ['run-script', 'prebuild:apijson']

  # Set firebase project
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['use', '$PROJECT_ID']
    secretEnv: ['FIREBASE_TOKEN']

  # Deploy to firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting', '--debug']
    secretEnv: ['FIREBASE_TOKEN']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'dist/apps/api'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker build -t gcr.io/$PROJECT_ID/monorock-api:latest -f Dockerfile --build-arg BUILD_COMMIT=$SHORT_SHA .',
      ]
  # Push Images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monorock-api:latest']
  # Deploy API to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'monorockapi',
        '--image',
        'gcr.io/$PROJECT_ID/monorock-api',
        '--region',
        us-central1,
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

secrets:
  - kmsKeyName: projects/monorock/locations/global/keyRings/monorock-integration-secrets/cryptoKeys/monorock-firebase-token
    secretEnv:
      FIREBASE_TOKEN: CiQAy0NVR7SUUqDhfL1ij6knHd9sIiLX/kgy8pBEeUPIBWnF3vwSkAEAlioXGAphMnchTae3mzJ8Mav88uqFX4AgZj9s5qnkXEmSsTdgNcKd+7E+XvMoY0tDfLHh4kjFZEjsVUhE30FORC6+rDmrdaSEYpJNJ7tmJ14mrWvhLAz7AOLAqoFA0l0+yGdiM2UQYPnU4xkx51uJgtu1AS146XaVgOjk69UpyTVF1r/twGSl8Jx7cmqbGAY=
